# Generated by Django 3.2.6 on 2021-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_controlpoint_last_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightstrip',
            name='gpio_control_pin',
            field=models.IntegerField(null=True),
        ),
    ]
