# Generated by Django 3.2.6 on 2021-08-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lightstrip_gpio_control_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightstrip',
            name='gpio_control_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
