# Generated by Django 3.2.6 on 2021-08-17 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('last_checkin', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightStrip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brightness', models.IntegerField(default=100)),
                ('control_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.controlgroup')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.controlpoint')),
            ],
        ),
    ]
