# Generated by Django 3.2.6 on 2021-08-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
